### PR TITLE
Distinguish markdown from content visually

### PR DESCRIPTION
**Pull request by trevorhreed**

### CODE REVIEW

**Comment by WesCossick** [comment]
Can you use that JSFiddle to demonstrate the difference this PR makes?

**Comment by trevorhreed** [comment]
Here's the updated JSFiddle, demonstrating the stylistic changes to format characters to help distinguish them from normal content characters: https://jsfiddle.net/08owwqvu/1/ 

Before:
screen shot 2016-12-06 at 4 02 27 pm

After:
screen shot 2016-12-06 at 4 02 13 pm

**Comment by WesCossick** [comment]
I'm not necessarily sure if I like this change. The Markdown syntax is important and shouldn't be so hidden.

**Comment by danabrey** [comment]
Personally, I think that the importance of the Markdown syntax isn't reduced, and may even help users inexperienced in Markdown syntax understand what is happening behind the scenes.

I understand not wanting to include this by default, though.

**Comment by WesCossick** [comment]
Because this is just three lines of CSS, I think I'll let this be something that a developer adds after-the-fact if it's important to them. I don't think it's a great inclusion for the default CSS. Maybe one day SimpleMDE will support themes, and this could be one variant offered.

**Pull request closed without merging**
