### PR TITLE
Gives users the ability to change editor's keyboard shortcuts

### LINKED ISSUE #169: Shortcuts turning off
Hi,

I need to know how to turn off all of shortcuts. When I press L + ALT it gives me ordered list. My language is polish so I need " ł " character insteed of list.

### PR DESCRIPTION
**Pull request by trwired**
Allows users to configure keyboard shortcuts. The shortcuts are then correctly reflected in the toolbar's tooltips. Indirectly fixes #169 by allowing the user to alter the problematic ones. (Which is an issue I am also experiencing. I suspect that Ctrl+Alt+[letter] default combinations are quite a headache for many non-English speakers.)

Here's the JSFiddle: https://jsfiddle.net/trwired/m7bptd95/

### CODE REVIEW

**Comment by WesCossick** [comment]
This should be a handy new option! Just a few changes needed though, before I can merge it. 
- You'll need to document this new option in the README and update any documentation that's now changed.
- If the `title` attribute is not an array (aka any version of SimpleMDE before this goes live), you'll need to handle it for backward compatibility. See [this fiddle](https://jsfiddle.net/nudoqdrj/) for an example of what I mean. Currently, if the title attribute is a string, it'll just pull the first character.

**Comment by WesCossick** [comment]
Heads up, a new PR was merged that causes some conflicts. Please update your branch to the latest code as well.

**Comment by trwired** [comment]
All done.

In hindsight the change to toolbar options was kind of awkward and not really necessary. I made configurable shortcuts work without it.

**Comment by WesCossick** [comment]
Great, thanks.

**Pull request merged**
