### PR TITLE
Add Support UMD

### PR DESCRIPTION
**Pull request by whiterm**

### CODE REVIEW

**Comment by WesCossick** [comment]
Thanks for submitting this PR @PhantomXCool. Can you describe the benefit of structuring the project this way?

**Comment by whiterm** [comment]
Simplemde failed during initialization in projects where amd (http://requirejs.org/docs/whyamd.html) is responsive for js downloading. I have added UMD support (http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/) to download js library everywhere it is necessary (with amd modules and without it). Also I have clearly marked the dependence for this module in package.json.
I have delegate Browserify (http://browserify.org/) to compile UMD libraries. 
PS. I recommend to upload the compiled library simplemde in bower (http://bower.io/) for more convenient using on client side in browser.

**Comment by WesCossick** [comment]
Questions/concerns:
- Regarding `.gitignore`:
  - The `/dist/` folder cannot be ignored, jsDelivr uses it for the CDN source
  - What are the `*.iml`, `*.ipr`, `*.iws` files?
- The `/dist/` folder probably doesn't need the debug file or the non-minified file
- CodeMirror only releases updates every month or so. Instead of adding them as a NPM dependency, updates can occur much more frequently if gulp.js continues to download the latest source files as previously set up.

**Comment by whiterm** [comment]
- Regarding .gitignore:
  - In some projects, for example, in angular, there is a division on the source files and compiled ones. But it is also possible to leave the /dist/ folder and to commit it.
  - This file type is used in IDE Idea that I use for developing.
- Debug file contains source map, but non-minified file contains only the source js.
- You may use dependency on github example `"codemirror": "codemirror/CodeMirror"`

**Comment by WesCossick** [comment]
Can you make the following changes:
- Do not ignore the `/dist/` folder.
- Do not ignore your IDE specific files. It's better to just untrack them locally since they don't relate to SimpleMDE specifically.
- Place the source map file in a new `/debug/` folder, along with the non-minified JS file. Also add the non-minified CSS file. Don't add these to the `/dist/` folder.
- Require [tablist.js](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/codemirror/tablist.js). This is a custom file created for SimpleMDE.
- Incorporate spell checking. This feature cannot be removed.
- Find a way to use the latest commits from CodeMirror's GitHub repository. Even changing it to `"codemirror": "codemirror/CodeMirror"` only uses the latest release on GitHub. Releases only happen once a month for CodeMirror, while commits to master occur every few days.

**Comment by whiterm** [comment]
Many projects in the ".gitignore" has .idea, *.iml. (Example CodeMirror, angular)

**Comment by whiterm** [comment]
A change it to `codemirror": "codemirror/CodeMirror"` use the latest commits from CodeMirror's GitHub repository

**Comment by WesCossick** [comment]
Almost everything looks good. Before I merge this, can you move the non-minified compiled JS file to the `/debug/` directory from the `/dist/` directory?

**Comment by WesCossick** [comment]
Also, the CSS files need to be compiled in this order:
1. CodeMirror
2. SimpleMDE
3. Spell Checker

**Comment by WesCossick** [comment]
And the JS files too, they need to be compiled in this order:

```
"./src/js/codemirror/codemirror.js",
"./src/js/codemirror/continuelist.js",
"./src/js/codemirror/tablist.js",
"./src/js/codemirror/fullscreen.js",
"./src/js/codemirror/markdown.js",
"./src/js/codemirror/overlay.js",
"./src/js/codemirror/gfm.js",
"./src/js/codemirror/xml.js",
"./src/js/typo.js",
"./src/js/spell-checker.js",
"./src/js/marked.js",
"./src/js/simplemde.js"
```

**Comment by whiterm** [comment]
I have done it

**Comment by WesCossick** [comment]
Looks great! I think that's everything.

**Pull request merged**
