### PR TITLE
Allow to disable syncing scroll in side-by-side mode via options

### PR DESCRIPTION
**Pull request by ggtmtmgg**
In the situation using a lot of images, syncing the scroll bar in side-by-side is not comfortable.
Because there is much difference between the editor side height and the preview side height.
Here is a sample for the situation:
https://jsfiddle.net/awjecc/0kmk9dxf/4/

So I add options for disabling syncing the scroll bar.
Here is a sample for how it works:
https://jsfiddle.net/awjecc/0kmk9dxf/3/

### CODE REVIEW

**Comment by WesCossick** [comment]
Hmm, the JSFiddles don't seem to load. Can you fix the RawGit URLs that so we can see the before/after comparison?

**Comment by ggtmtmgg** [comment]
It used the RawGit URLs for development.
It's fixed to use the URLs for production.

**Comment by WesCossick** [comment]
Thanks, I like this option. A few things before I can merge it in:

1. Rename the option to `syncSideBySidePreviewScroll`
1. Place the option documentation in correct alphabetical order
1. Add the example non-default usage in the block of code beneath the options list
1. Don't commit `dist/simplemde.min.js` to this PR

**Comment by ggtmtmgg** [comment]
I've fixed all four things.
You can check it out how it's working from here. https://jsfiddle.net/awjecc/0kmk9dxf/6/

**Pull request merged**
