### PR TITLE
Added undo and redo buttons to toolbar

### PR DESCRIPTION
**Pull request by JamieWohletz**
Added undo and redo buttons to the toolbar as suggested in https://github.com/NextStepWebs/simplemde-markdown-editor/issues/203. 

See [this fiddle](https://jsfiddle.net/L97sswa2/) to see how the updated toolbar looks and works.

### CODE REVIEW

**Comment by WesCossick** [comment]
Thanks for the PR! Can you remove `default: true` from the undo/redo buttons?

**Comment by JamieWohletz** [comment]
@WesCossick sure!

**Comment by jesseleite** [comment]
Awesome!  I have a client who was asking for this.  Saves me the time having to extend myself, thanks :)

**Comment by JamieWohletz** [comment]
@JesseLeite glad it can be of use :smile:

**Pull request merged**
