### PR TITLE
Adds Gulpfile and a few extra options

### PR DESCRIPTION
**Pull request by frm**
Dependencies can be installed with `npm install`. Then, running `gulp` should minify all `.js` and `.css` files. JavaScript files are located under `src/js` and CSS files are located under `src/css`, to simplify the gulp tasks.

There is no correct order for CSS minification, but the JS files are minified according to the order stated in [here](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/source%20files/README.md).

Also added a couple of options:
- Calling `editor.value('')` now clears the editor content.
- Passing `defaultValue` in the constructor object sets the first editor value when rendered.

Shout out to @nofxx, thank you for your help.

### CODE REVIEW

**Comment by WesCossick** [comment]
A few changes before I can merge this:
- `src/css/spell-checker.css` is outdated and needs to be updated
- `src/css/theme.css` needs to be renamed to `simplemde.css` and updated

**Comment by frm** [comment]
Ups, my bad. I missed that during the rebase.

From what I saw, `src/css/simplemde.css` is the same as the current version of this branch. `src/css/theme.css` just needs to be removed, as it is the older version.

**Comment by WesCossick** [comment]
Thanks. I'll include these changes in the next release.

**Comment by WesCossick** [comment]
Just a heads up, I renamed `defaultValue` to `initialValue` for more clarity as to its purpose.

**Pull request merged**
