### PR TITLE
Add jQuery validation example to the documentation

### PR DESCRIPTION
**Pull request by BboyKeen**
I've searched during a few hours to find a way to mimic the jQuery validation with the editor.
I've tried a lot of things but I think this one is the best one.

I've added a sample code to the documentation to show how to perform jQuery validation. If you need a jsFiddle to show you it works, please let me know.

### CODE REVIEW

**Comment by WesCossick** [comment]
Hey @BboyKeen, this is a bit too specific of an example to include in the documentation. Thanks for the submission though.

**Comment by WesCossick** [comment]
For version 2.0.0, I'll be creating a dedicated website for SimpleMDE with the documentation organized into multiple pages. It'll be much easier to add specific documentation like this without creating one really long Markdown document like how it works now on GitHub's site. So I'll keep this PR in mind.

**Comment by BboyKeen** [comment]
Hey @WesCossick.

Thanks for your feedback. Keep me in touch when the website will be available.
By the way, will the version 2.0.0 introduce some BC breaks ?

**Comment by WesCossick** [comment]
You can follow the progress via [this milestone](https://github.com/NextStepWebs/simplemde-markdown-editor/milestones/2.0.0-beta1). The goal is to keep 100% backwards compatibility with every update, including version 2.

**Pull request closed without merging**
