### PR TITLE
add placeholder option

### PR DESCRIPTION
**Pull request by adam187**
it will work with custom placeholder via configuration option or placeholder attribute from textarea element.

Referring comments from https://github.com/NextStepWebs/simplemde-markdown-editor/pull/198#issuecomment-163431744:
- Code updated
- <del>I will prepare JSField examples later today.</del> http://jsfiddle.net/adam187/515j9vgb/

### CODE REVIEW

**Comment by adam187** [comment]
@WesCossick jsfiddle example ready. http://jsfiddle.net/adam187/515j9vgb/

**Comment by WesCossick** [comment]
Looking good. One last change, can you replace the four spaces before `placeholder: "Type here...",` in the README with a single tab character?

**Comment by WesCossick** [comment]
Actually one more change. I think it'd look nice if the following CSS rule was added as well:

``` CSS
.CodeMirror .CodeMirror-placeholder{
    opacity: .5;
}
```

**Comment by adam187** [comment]
@WesCossick PR and example updated.

**Comment by WesCossick** [comment]
Thanks.

**Pull request merged**
