### PR TITLE
Prompt for the number of columns and rows while inserting a table

### PR DESCRIPTION
**Pull request by jonatanklosko**
When the user clicks on the 'Insert table' icon, then two alerts appear one by one asking for the number of columns and rows accordingly.
Such a behavior should be more user-friendly.

Here's a demo: https://jsfiddle.net/45fL71nh/.

### CODE REVIEW

**Comment by jonatanklosko** [comment]
What's wrong with the tests? I cannot see any relation with this PR.

**Comment by WesCossick** [comment]
Look at the details. There's a syntax error: https://travis-ci.org/NextStepWebs/simplemde-markdown-editor/jobs/143317653.

**Comment by WesCossick** [comment]
To be honest though, I'm not a big fan of using alerts. There's probably a better way of accomplishing this using DOM elements and inputs.

**Comment by jonatanklosko** [comment]
Right, I don't like browser alerts too. I've update the code to use [Sweet Alert 2](https://limonte.github.io/sweetalert2/).
Here's the updated demo: https://jsfiddle.net/45fL71nh/3.
Main points:
- link/image URLs can be entered nicely with the new alerts
- table row/column count inputs are validated nicely (try to enter negative values or any text)

I'm not sure whether I've set up dependencies correctly (require/css compilation/package.json).

**Comment by WesCossick** [comment]
I appreciate the effort, but I'd like to avoid bundling any dependencies that aren't absolutely necessary. Sweet Alert is nice, but it's overkill for the job. I may just tackle this for version 2.0 in the future.

**Pull request closed without merging**
