### PR TITLE
add ability to set up markup for bold and italic

### PR DESCRIPTION
**Pull request by adam187**

### CODE REVIEW

**Comment by WesCossick** [comment]
Before I can merge this, please make a few changes to keep the README consistent:
- Place the `blockStyles` description in correct alphabetical order.
- Add example usage for the non-default behavior to the code block that demonstrates every option.
- Add trailing periods after both `Defaults to...` lines.

**Comment by adam187** [comment]
@WesCossick Updated :)

**Comment by WesCossick** [comment]
Sorry to be so picky, but I hate when other projects have inconsistent or misleading documentation, so I'm doing my best to keep SimpleMDE's as high quality as possible.

With that said, can you change `bold: "**",` to `bold: "__",` to demonstrate the non-default behavior?

**Comment by adam187** [comment]
@WesCossick Sure, totally makes sense. Updated :)

**Comment by WesCossick** [comment]
Thanks

**Pull request merged**
