### PR TITLE
Fixed ordered list markers. #212

### PR DESCRIPTION
**Pull request by kfprimm**
Hi there,

I recently had a few users confused by #212, so I whipped together (what I hope is) a reasonable solution.

Thanks!

### CODE REVIEW

**Comment by WesCossick** [comment]
Can you throw together a JSFiddle that demonstrates this fix? I'd like to make sure it works well and gather other's feedback before merging it in.

**Comment by webriq** [comment]
I can confirm the above code changes work. Before when you highlight a list of items (nth line) and hit the `Numbered List` toggle, it results to the list preceded each with number 1. But testing this PR, it changed to a consecutive numbers 1 to nth. Thanks

**Comment by FabianKoestring** [comment]
@kfprimm Can you fix the failing test?

**Comment by TangentFoxy** [comment]
The failing check looks like it's an error with gulp...and even if it isn't, has nothing to do with this change.

**Pull request closed without merging**
