### PR TITLE
Context aware code button

### PR DESCRIPTION
**Pull request by brondsem**
The code button now inspects the current selection and/or cursor position to detect if it should add a multi-line code block or inline code formatting.  It detects the current state of the markdown, to toggle them off correctly, additionally handling indented blocks too.  It can even un-code-block a section in the middle of a large code block.  It supports a new `editor.options.blockStyles.code` setting to allow for those who prefer tildes rather than backticks.

### CODE REVIEW

**Comment by WesCossick** [comment]
This looks really great! Can you set up a JSFiddle for me (and others) to play around with it before I merge it in?

**Comment by brondsem** [comment]
Looks like there is an issue when spellChecker is enabled, I'll have to look into it further...

**Comment by brondsem** [comment]
Fixed for spellChecker now.  Here's a demo: https://jsfiddle.net/b64nz5e8/5/

**Comment by WesCossick** [comment]
Almost everything looks fantastic, though I did notice one inconsistency. If you highlight the entire second block of code in the first textarea in the JSFiddle, then click the code button, it adds more tick marks instead of taking them away.

**Comment by brondsem** [comment]
Ah, yeah.  I can take a look at fixing that.  If you select less than that, like a single line, it will add ticks so that the single line is not a code block and it is now surrounded by 2 code blocks.  But if you have the whole thing selected that doesn't make sense any more :)

**Comment by WesCossick** [comment]
Got it, thanks again for your work on this!

**Comment by brondsem** [comment]
Updated.

**Comment by WesCossick** [comment]
Perfect, looks really great. I've merged it in, so it'll go out with the next release.

**Pull request merged**
