### PR TITLE
Added bower support

### LINKED ISSUE #129: Bower support
What about adding bower support?

### PR DESCRIPTION
**Pull request by FabianKoestring**
Simple support to install this package via bower. The package is already in the bower registry.
This is my first try. I hope everything work as expected.

Fix #129

### CODE REVIEW

**Comment by WesCossick** [comment]
Thanks!

**Comment by WesCossick** [comment]
Actually, can you compare against the `development` branch in a new PR?

**Comment by WesCossick** [comment]
Nevermind, I just committed the changes manually to the dev branch

**Comment by FabianKoestring** [comment]
Works?

**Comment by WesCossick** [comment]
Works great. I resubmitted it to bower's registry as `simplemde` to match npm's package name.

**Comment by FabianKoestring** [comment]
:+1:

**Pull request merged**
