### PR TITLE
Added a parameter to pass in highlight.js in from the renderConfig

### PR DESCRIPTION
**Pull request by mrsimonemms**
Started with #396 

Previously, if you wanted to use highlight.js to render the preview, you had to have hljs on the window object. In practice, this is poor and negates many of the
principles behind using Browserify. By injecting it in as a parameter, this means the client can avoid adding things to their global scope if they don't/can't
avoid that.

This is a non-breaking change, only adding a new option to an existing API. The default behaviour is unchanged

### CODE REVIEW

**Comment by mrsimonemms** [comment]
As a non-breaking API change, suggest this is released as `v1.12.0`

**Comment by WesCossick** [comment]
Thanks. The goal of all SimpleMDE updates (major/minor/patch) is to be non-breaking.

**Comment by mrsimonemms** [comment]
When might this get released?

**Comment by WesCossick** [comment]
No estimate at the moment. Usually when enough changes pile up and I have enough time on my hands. Currently, I'm very short of the latter.

**Comment by mertkahyaoglu** [comment]
Looking forward to this 👍

**Pull request merged**
