### PR TITLE
Provide an onChange callback

### PR DESCRIPTION
**Pull request by anderslemke**
I'm integrating SimpleMDE into React, hence, the `onChange` is really handy.

### CODE REVIEW

**Comment by CodyJamesCasey** [comment]
@anderslemke I didn't look too deeply into your PR, but I am using SimpleMDE with React and I am able to hook into the codemirror change handler. Does this satisfy what you are going for?

```
    simplemde.codemirror.on("change", () => {
      this.setState({
        value: simplemde.value(),
      )};
    });
```

**Comment by anderslemke** [comment]
It definitely would, @CodyJamesCasey ! :)
I wasn't aware that the `codemirror` was exposed like that.

So, now the question is, should SimpleMDE expose such internals for developers to hook into, or provide the callback.

I think would argue for the latter.
When being a developer using SimpleMDE, CodeMirror is an internal implementation to SimpleMDE detail that I do not want to care about.

But I don't know the architecture of SimpleMDE too well, and if CodeMirror can be excanged with something else by the developer.

**Comment by CodyJamesCasey** [comment]
@anderslemke  I can't say much because I also implemented my own `onChange` at first before reading. However, it is in the docs under `Event handling` ;)

I think I agree with you that it would be better have everything wrapped and provided by SimpleMDE directly instead of the exposed `codemirror`. I also haven't dug deeply enough to have a solid thought on it though!

**Comment by anderslemke** [comment]
Wow. I didn't see it in the docs. My bad! I think I'll close this for now. :)

**Pull request closed without merging**
